### ISSUE TITLE
Select all filtered results checkbox not getting checked With Group By

### ISSUE THREAD

**Issue by vijendrakumar** [CuppaLabs/angular2-multiselect-dropdown#347] opened 2019-02-01 11:25 UTC
Select all filtered results checkbox not getting checked with Group By of list feature.
Throwing below mentioned error in console.
ERROR TypeError: Cannot read property 'forEach' of undefined

**Comment by pwinstead** [comment] 2019-02-05 15:13
I believe this is a duplicate of issue #334.  Unfortunately, there is no resolution yet.

**Comment by CuppaLabs** [comment] 2019-08-18 19:48
Fixed. ix available in 4.5.0

**Closed by CuppaLabs** 2019-08-18 19:48 UTC
