### ISSUE TITLE
modifying search filter does not update results until I click within the search/filtering component

### ISSUE THREAD

**Issue by lain-mack** [CuppaLabs/angular2-multiselect-dropdown#534] opened 2020-11-18 19:44 UTC
I have the following options set for my dropdown:
```
{
    singleSelection: true,
    enableSearchFilter: true,
    addNewItemOnFilter: true
}
```

Unless I click within the search/filtering component after typing a letter, the filter used is one letter behind what I've typed.

Angular 10
angular2-multiselect-dropdown v4.2.1

**Comment by jpr303** [comment] 2020-11-19 22:35
This is a duplicate of #524

**Closed** 2020-11-24 17:02 UTC
