### ISSUE TITLE
Data not bind

### ISSUE THREAD

**Issue by girishghoda** [CuppaLabs/angular2-multiselect-dropdown#198] opened 2018-03-21 07:36 UTC
@silkyfray @pickardjoe @CuppaLabs Hi team,

A) Home component, Detail component
B) Navigate Home component to Detail component
C) Angular2Multiselect dropdown implemented in Detail component
D) a) Normally navigate to Detail component multiselect works fine
     b) Navigate from observable.subscribe block then multiselect not show any data or not work click 
         event
 
Sample data : 
Put below code  in ngOnInit()
itemList = [
      { "id": 1, "itemName": "Accessories", "category": "Apparel & Footwear" },
      { "id": 2, "itemName": "Activewear", "category": "Apparel & Footwear" },
      { "id": 3, "itemName": "Swimwear", "category": "Apparel & Footwear" },
      { "id": 4, "itemName": "Athletic", "category": "Apparel & Footwear" },
      { "id": 5, "itemName": "Lifestyle", "category": "Apparel & Footwear" },
      { "id": 6, "itemName": "Equipment & Gear", "category": "Sports & Recreation" },
      { "id": 7, "itemName": "Electronics", "category": "Sports & Recreation" },
      { "id": 8, "itemName": "Wearable devices", "category": "Sports & Recreation" },
      { "id": 9, "itemName": "Tactical", "category": "Sports & Recreation" }
    ];

    this.selectedItems = [];
    this.settings = {
      singleSelection: false,
      text: "Select Categories",
      selectAllText: 'Select all',
      unSelectAllText: 'Deselect all',
      enableSearchFilter: true,
      badgeShowLimit: 2,
      classes: "myclass custom-class-dropdown",
      groupBy: "category"
    };

Attach screen shot
![screen shot 2018-03-21 at 1 07 14 pm](https://user-images.githubusercontent.com/19307918/37698351-840eb714-2d08-11e8-8054-3311ad937a7d.png)

Any suggestion
Thank you

**Comment by CuppaLabs** [comment] 2018-03-23 18:46
Please install the package & implement it correctly. Its an implementation issue in you project and not a bug in component. Hence closing.

**Closed by CuppaLabs** 2018-03-23 18:46 UTC
