### ISSUE TITLE
Customizable selected item

### ISSUE THREAD

**Issue by SSlippa** [CuppaLabs/angular2-multiselect-dropdown#122] opened 2017-12-28 15:20 UTC
Hi,
There is not enough opportunity to make custom selected item, for example put image like in options of select.

![capture](https://user-images.githubusercontent.com/28702758/34414709-6fa0e55a-ebf3-11e7-890e-d4738cc70cbf.PNG)

**Comment by CuppaLabs** [comment] 2018-01-06 12:58
duplicate of #115

**Closed** 2018-01-06 12:58 UTC
Labels: duplicate
