### ISSUE TITLE
Message if result of listFilter is empty

### ISSUE THREAD

**Issue by andi-wr** [CuppaLabs/angular2-multiselect-dropdown#118] opened 2017-12-20 07:56 UTC
Hi,

first of all: I really like this component, good work! :+1: 

I use the dropdown with the groupBy settings active and enableSearchFilter enabled. I have a lot of groups. When I apply a search filter which results in an empty result, I see all the plenty headings of the groups, but it's not obvious that there's no item that matches my search term. Is it possible to integrate the possibility to display a message if listFilter results in an empty list?

Thanks!

**Comment by CuppaLabs** [comment] 2017-12-20 17:18
duplicate of #107

**Closed by CuppaLabs** 2017-12-20 17:18 UTC
