### ISSUE TITLE
is there a way to select all within a group?

### ISSUE THREAD

**Issue by ArunPrasathSubramani** [CuppaLabs/angular2-multiselect-dropdown#215] opened 2018-04-05 16:45 UTC
Before I begin, thank you very much. Its a great utility.

I am looking for a feature of selecting a group of items. 
Group by is working, is there a way I can have a checkbox for the group by header and select all inside that group only.???

**Comment by ArunPrasathSubramani** [comment] 2018-04-05 17:06
If the category can be accepted as template, that could solve this functionality.

**Comment by CuppaLabs** [comment] 2018-04-05 19:08
duplicate of #69

**Closed by CuppaLabs** 2018-04-05 19:08 UTC

**Comment by suresh2018** [comment] 2018-05-03 12:18
hi oi need this feature ..please tel how to do

**Comment by suresh2018** [comment] 2018-05-03 12:31
currently this feature possible ?

**Comment by sweetyv** [comment] 2018-05-04 10:14
Hi, even I need this feature for my project urgently. Could you please help @CuppaLabs ? 
Thank you in advance.

**Comment by GustavoLima93** [comment] 2018-06-12 13:01
Hello @CuppaLabs Thanks a lot for the angular2-multiselect-dropdown this is advancing my life a lot, I would like my colleagues to select this feature by group, I tried to understand the angular2-multiselect-dropdown core to implement the functionality but I could not do it unhappily I do not have the same level of maturity that you, I would like to know if you have any date to implement the functionaldiade? Thanks in advance.
