### ISSUE TITLE
Angular4 compliance

### ISSUE THREAD

**Issue by policz** [CuppaLabs/angular2-multiselect-dropdown#78] opened 2017-11-01 01:46 UTC
I followed same instructions on angular4 project it giving errors.
```code
core.es5.js:1020 ERROR Error: Uncaught (in promise): Error: Template parse errors:
Can't bind to 'data' since it isn't a known property of 'angular2-multiselect'.
1. If 'angular2-multiselect' is an Angular component and it has 'data' input, then verify that it is part of this module.
2. If 'angular2-multiselect' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
3. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. ("m dropdown">
                <div class="form-group">      
                <angular2-multiselect [ERROR ->][data]="dropdownList" [(ngModel)]="selectedItems" 
                [settings]="dropdownSettings" 
 "): ng:///AutomatedModule/AutomatedComponent.html@100:38
Can't bind to 'settings' since it isn't a known property of 'angular2-multiselect'.
1. If 'angular2-multiselect' is an Angular component and it has 'settings' input, then verify that it is part of this module.
2. If 'angular2-multiselect' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
3. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. ("          <angular2-multiselect [data]="dropdownList" [(ngModel)]="selectedItems" 
                [ERROR ->][settings]="dropdownSettings" 
                (onSelect)="onItemSelect($event)" 
                ("): ng:///AutomatedModule/AutomatedComponent.html@101:16
'angular2-multiselect' is not a known element:
1. If 'angular2-multiselect' is an Angular component, then verify that it is part of this module.
2. If 'angular2-multiselect' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message. ("    <li class="nav-item dropdown">
                <div class="form-group">      
                [ERROR ->]<angular2-multiselect [data]="dropdownList" [(ngModel)]="selectedItems" 
                [settings]="): ng:///AutomatedModule/AutomatedComponent.html@100:16
Error: Template parse errors:
Can't bind to 'data' since it isn't a known property of 'angular2-multiselect'.
1. If 'angular2-multiselect' is an Angular component and it has 'data' input, then verify that it is part of this module.
2. If 'angular2-multiselect' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
3. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. ("m dropdown">
                <div class="form-group">      
                <angular2-multiselect [ERROR ->][data]="dropdownList" [(ngModel)]="selectedItems" 
                [settings]="dropdownSettings" 
 "): ng:///AutomatedModule/AutomatedComponent.html@100:38
Can't bind to 'settings' since it isn't a known property of 'angular2-multiselect'.
1. If 'angular2-multiselect' is an Angular component and it has 'settings' input, then verify that it is part of this module.
2. If 'angular2-multiselect' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
3. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. ("          <angular2-multiselect [data]="dropdownList" [(ngModel)]="selectedItems" 
                [ERROR ->][settings]="dropdownSettings" 
                (onSelect)="onItemSelect($event)" 
                ("): ng:///AutomatedModule/AutomatedComponent.html@101:16
'angular2-multiselect' is not a known element:
1. If 'angular2-multiselect' is an Angular component, then verify that it is part of this module.
2. If 'angular2-multiselect' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message. ("    <li class="nav-item dropdown">
                <div class="form-group">      
                [ERROR ->]<angular2-multiselect [data]="dropdownList" [(ngModel)]="selectedItems" 
                [settings]="): ng:///AutomatedModule/AutomatedComponent.html@100:16
```

**Comment by CuppaLabs** [comment] 2017-11-01 06:28
You should import formsModule in your project. It's not a version issue

**Comment by CuppaLabs** [comment] 2017-11-01 06:50
The component in compliant with Angular v4.0.0 . Please refer to the dependencies at https://github.com/CuppaLabs/angular2-multiselect-dropdown/blob/master/package.json
Hence closing the issue. If the issue is related to anything else, please raise it appropriate steps to reproduce. Also, refer to plunker https://plnkr.co/edit/fof4c6PBadEfZFnaWT2G?p=preview

**Closed by CuppaLabs** 2017-11-01 06:50 UTC
