### ISSUE TITLE
TypeError: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by Syedmusthafa** [CuppaLabs/angular2-multiselect-dropdown#6] opened 2017-05-24 11:59 UTC
I Get This, When  Loading Our Application.
![image](https://cloud.githubusercontent.com/assets/28923436/26402082/7bc679a6-40a6-11e7-8ff4-2b179d58de1b.png)

**Comment by CuppaLabs** [comment] 2017-05-25 04:53
Hi, Could you please provide the test case and steps to reproduce the issue ?

**Comment by CuppaLabs** [comment] 2017-05-28 06:15
cannot reproduce. Hence, closing.

**Closed by CuppaLabs** 2017-05-28 06:15 UTC
Labels: bug

**Comment by DZcoderX** [comment] 2017-11-03 18:21
I'm getting the same error, I'm getting data from a server 
The error shows up whenever I select an item from the dropdownList
It's giving me this error: 

```
ERROR TypeError: Cannot read property 'length' of undefined
    at AngularMultiSelect.webpackJsonp.../../../../angular2-multiselect-dropdown/angular2-multiselect-dropdown/multiselect.component.js.AngularMultiSelect.onItemClick (multiselect.component.js:58)
    at Object.eval [as handleEvent] (AngularMultiSelect.html:36)
    at handleEvent (core.es5.js:11892)
    at callWithDebugContext (core.es5.js:13184)
    at Object.debugHandleEvent [as handleEvent] (core.es5.js:12772)
    at dispatchEvent (core.es5.js:8792)
    at core.es5.js:9384
    at HTMLLIElement.<anonymous> (platform-browser.es5.js:2683)
    at ZoneDelegate.webpackJsonp.../../../../zone.js/dist/zone.js.ZoneDelegate.invokeTask (zone.js:414)
    at Object.onInvokeTask (core.es5.js:4119)
```

I am currently running this code:

```
dropdownList: Array<{}> = [];
dropdownSettings = {};

ngOnInit(){
      this.onGet(); --> Gets the data from the server (method is below) 
      
      this.dropdownSettings = {
        singleSelection: false,
        text:"Select Countries",
        selectAllText:'Select All',
        unSelectAllText:'UnSelect All',
        enableSearchFilter: true,
        classes:"myclass custom-class",
        limitSelection: 6,
        badgeShowLimit: 3
      };
      
  }

onGet(){
    this.brokerService.getFilters() 
    .subscribe(
      (dropdownList: any[]) => {
        this.dropdownList = dropdownList; -->The this.dropdownList is now a json object array (exact same format as the static one given your tutorial
        console.log(this.dropdownList); // (confirms it's the exact same format) 
        },
      (error)=> console.log(error)
    );
  }
```
