### ISSUE TITLE
Bind dropdown list dynamically

### ISSUE THREAD

**Issue by monalipatwa** [CuppaLabs/angular2-multiselect-dropdown#236] opened 2018-04-24 06:14 UTC
How can we bind dropdown list dynamically? I am getting following error.. I have used multiselect in *ngFor:

`this.selectedItems.forEach is not a function`

I have used multiselect as follows:

```
<div *ngFor="let input of Task.inputArr; let parentIndex = index">
       <angular2-multiselect [data]="input.list" [(ngModel)]="input.outputValue" 
                   [settings]="dropdownSettings2" [disabled] = "viewTaskFlag" class="input-sm">
          <c-item>
                 <ng-template let-item="item">
                             <label style="color: #333;min-width: 150px;">{{item.itemName}}</label>
                   </ng-template>
           </c-item>    
      </angular2-multiselect>
</div>
```

**Comment by CuppaLabs** [comment] 2018-04-24 12:14
This is an implementation issue and not a bug with the component. Please drop a mail for any queries. Hence closing.

**Closed by CuppaLabs** 2018-04-24 12:14 UTC
